"""Initial schema

Revision ID: 8e88e85ffe40
Revises: 
Create Date: 2026-02-27 20:02:37.545127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '8e88e85ffe40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_source_type', 'rag_documents', ['source_type'], unique=False)
    op.create_index(op.f('ix_rag_documents_id'), 'rag_documents', ['id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_table('quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('quota_type', sa.String(length=50), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'quota_type', 'period', name='uq_teacher_quota_period')
    )
    op.create_index('idx_quota_teacher_type', 'quotas', ['teacher_id', 'quota_type'], unique=False)
    op.create_index(op.f('ix_quotas_id'), 'quotas', ['id'], unique=False)
    op.create_index(op.f('ix_quotas_teacher_id'), 'quotas', ['teacher_id'], unique=False)
    op.create_table('streaming_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_teacher_active', 'streaming_sessions', ['teacher_id', 'is_active'], unique=False)
    op.create_index('idx_session_youtube_video', 'streaming_sessions', ['youtube_video_id'], unique=False)
    op.create_index(op.f('ix_streaming_sessions_id'), 'streaming_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_streaming_sessions_teacher_id'), 'streaming_sessions', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_streaming_sessions_youtube_video_id'), 'streaming_sessions', ['youtube_video_id'], unique=False)
    op.create_table('youtube_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', name='uq_teacher_youtube_token')
    )
    op.create_index(op.f('ix_youtube_tokens_id'), 'youtube_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_tokens_teacher_id'), 'youtube_tokens', ['teacher_id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('centroid_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['streaming_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cluster_session', 'clusters', ['session_id'], unique=False)
    op.create_index(op.f('ix_clusters_id'), 'clusters', ['id'], unique=False)
    op.create_index(op.f('ix_clusters_session_id'), 'clusters', ['session_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('youtube_comment_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_channel_id', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_question', sa.Boolean(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['streaming_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_cluster', 'comments', ['cluster_id'], unique=False)
    op.create_index('idx_comment_session_answered', 'comments', ['session_id', 'is_answered'], unique=False)
    op.create_index('idx_comment_session_question', 'comments', ['session_id', 'is_question'], unique=False)
    op.create_index(op.f('ix_comments_cluster_id'), 'comments', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_session_id'), 'comments', ['session_id'], unique=False)
    op.create_index(op.f('ix_comments_youtube_comment_id'), 'comments', ['youtube_comment_id'], unique=True)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('youtube_comment_id', sa.String(length=255), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_comment_id')
    )
    op.create_index('idx_answer_cluster_posted', 'answers', ['cluster_id', 'is_posted'], unique=False)
    op.create_index(op.f('ix_answers_cluster_id'), 'answers', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_answers_comment_id'), 'answers', ['comment_id'], unique=False)
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_comment_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_cluster_id'), table_name='answers')
    op.drop_index('idx_answer_cluster_posted', table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_comments_youtube_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_session_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_cluster_id'), table_name='comments')
    op.drop_index('idx_comment_session_question', table_name='comments')
    op.drop_index('idx_comment_session_answered', table_name='comments')
    op.drop_index('idx_comment_cluster', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_clusters_session_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_id'), table_name='clusters')
    op.drop_index('idx_cluster_session', table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_youtube_tokens_teacher_id'), table_name='youtube_tokens')
    op.drop_index(op.f('ix_youtube_tokens_id'), table_name='youtube_tokens')
    op.drop_table('youtube_tokens')
    op.drop_index(op.f('ix_streaming_sessions_youtube_video_id'), table_name='streaming_sessions')
    op.drop_index(op.f('ix_streaming_sessions_teacher_id'), table_name='streaming_sessions')
    op.drop_index(op.f('ix_streaming_sessions_id'), table_name='streaming_sessions')
    op.drop_index('idx_session_youtube_video', table_name='streaming_sessions')
    op.drop_index('idx_session_teacher_active', table_name='streaming_sessions')
    op.drop_table('streaming_sessions')
    op.drop_index(op.f('ix_quotas_teacher_id'), table_name='quotas')
    op.drop_index(op.f('ix_quotas_id'), table_name='quotas')
    op.drop_index('idx_quota_teacher_type', table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_rag_documents_id'), table_name='rag_documents')
    op.drop_index('idx_rag_source_type', table_name='rag_documents')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
